FROM python:3

RUN apt-get update && apt-get install -y libaio1 wget unzip

WORKDIR /opt/oracle
RUN wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip && \
    unzip instantclient-basiclite-linuxx64.zip && rm -f instantclient-basiclite-linuxx64.zip && \
    cd /opt/oracle/instantclient* && rm -f *jdbc* *occi* *mysql* *README *jar uidrvci genezi adrci && \
    echo /opt/oracle/instantclient* > /etc/ld.so.conf.d/oracle-instantclient.conf && ldconfig

COPY ./app /python-server
COPY ./wallet /opt/oracle/instantclient/network/admin/

RUN pip install --upgrade pip

WORKDIR /python-server

RUN pip install -r requirements.txt



# CMD ["gunicorn", "-w","4", "-k", "uvicorn.workers.UvicornWorker", "backend.server.app_init:app"]
CMD ["python", "main.py"]
